name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
      with:
        swift-version: "5.3"
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.1'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
